### ISSUE TITLE
SOLR configuration

### ISSUE THREAD

**Issue by angelo337** [Norconex/committer-solr#8] opened 2016-09-03 03:31 UTC
hi there
I am trying to configure for the first time a commiter on SOLR system, however i did no manage to make it work, i mean to include new documents in the Solr.
could some one  please help me?
thanks
this is my config file:

<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Wikipedia HTTP Collector">
  <progressDir>./examples-output/minimum/progress</progressDir>
  <logsDir>./examples-output/minimum/logs</logsDir>
                <crawlers>
                  <crawler id="WikiCrawler">

```
                    <!-- Let's say we're crawling Wikipedia English in our example -->
                    <startURLs>
                      <url>http://en.wikipedia.org/</url>
                    </startURLs>
                    <numThreads>10</numThreads>
                    <importer>
                      <preParseHandlers>
                            <tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger">
                              <constant name="data_source">
                                      927df3075b544785892c6b4c51625714
                              </constant>
                              <constant name="data_source_type">Web</constant>
                              <constant name="data_source_name">Wikipedia</constant>
                            </tagger>
                      </preParseHandlers>
                    </importer>

                    <committer class="com.norconex.committer.solr.SolrCommitter">
                      <solrURL>http://127.0.0.1:8984/solr/collection1_shard1_replica1/</solrURL>
                      <targetContentField>body</targetContentField>
                      <queueSize>2</queueSize>
                      <commitBatchSize>25</commitBatchSize>
                    </committer>

              </crawler>
            </crawlers>
```

</httpcollector>

**Comment by essiembre** [comment] 2016-09-03 13:02
What indication  do you have it is not working?  Are you simply not seeing documents in Solr or do you have errors?  Can you please attach your log file?

**Comment by angelo337** [comment] 2016-09-03 22:54
hi there
thanks for your answer, here is the code that i Modify from and example I found in a git, of another product of your company.

``` xml
<httpcollector id="Minimal Config HTTP Collector">
    <crawlers>
        <crawler id="Minimal Solr Config Example">
            <!-- Requires at least one start URL. -->
            <startURLs>
                <url>http://lucene.apache.org/solr/</url>
            </startURLs>

            <!-- Put a maximum depth to avoid infinite crawling (e.g. calendars). -->
            <maxDepth>2</maxDepth>

            <!-- Be as nice as you can to sites you crawl. -->
            <delay default="1500" />

            <!-- At a minimum make sure you stay on your domain. -->
            <httpURLFilters>
                <filter class="$urlFilter"
                    onMatch="include">http://lucene.apache.org/solr/.*</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\.(png|jpg|jpeg|gif|ico|css|js)$</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\?.*</filter>
            </httpURLFilters>


            <!-- A "committer" dictates where the crawled content goes. -->
            <committer class="com.norconex.committer.solr.SolrCommitter">
                <solrURL>http://localhost:8984/solr/collection1</solrURL>
            </committer>

            <!-- When developing or troubleshooting, you can use the filesystem
                 committer so you can have a precise look at the content 
                 that would be sent to Solr. -->
            <!--
            <committer class="com.norconex.committer.impl.FileSystemCommitter">
                <directory>./examples-output/minimum/crawledFiles</directory>
            </committer>
            -->

        </crawler>
    </crawlers>
</httpcollector>
```

and here is the output:

```
> $ ./collector-http.sh -a start -c examples/config_base.xml 
/home/creangel/Downloads/solr/collector-http
INFO  [AbstractCollectorConfig] Configuration loaded: id=Minimal Config HTTP Collector; logsDir=./logs; progressDir=./progress
INFO  [JobSuite] JEF work directory is: ./progress
INFO  [JobSuite] JEF log manager is : FileLogManager
INFO  [JobSuite] JEF job status store is : FileJobStatusStore
INFO  [AbstractCollector] Suite of 1 crawler jobs created.
INFO  [JobSuite] Initialization...
INFO  [JobSuite] Previous execution detected.
INFO  [JobSuite] Backing up previous execution status and log files.
INFO  [JobSuite] Starting execution.
INFO  [AbstractCollector] Version: Norconex HTTP Collector 2.6.0 (Norconex Inc.)
INFO  [AbstractCollector] Version: Norconex Collector Core 1.6.0 (Norconex Inc.)
INFO  [AbstractCollector] Version: Norconex Importer 2.6.0 (Norconex Inc.)
INFO  [AbstractCollector] Version: Norconex JEF 4.0.7 (Norconex Inc.)
INFO  [AbstractCollector] Version: Norconex Committer Core 2.0.5 (Norconex Inc.)
INFO  [AbstractCollector] Version: Norconex Committer Solr 2.2.0 (Norconex Inc.)
INFO  [JobSuite] Running Minimal Solr Config Example: BEGIN (Sat Sep 03 17:44:03 COT 2016)
INFO  [HttpCrawler] Minimal Solr Config Example: RobotsTxt support: true
INFO  [HttpCrawler] Minimal Solr Config Example: RobotsMeta support: true
INFO  [HttpCrawler] Minimal Solr Config Example: Sitemap support: true
INFO  [HttpCrawler] Minimal Solr Config Example: Canonical links support: true
INFO  [HttpCrawler] Minimal Solr Config Example: User-Agent: <None specified>
INFO  [AbstractCrawler] Minimal Solr Config Example: Crawler executed in 0 second.
FATAL [JobSuite] Fatal error occured in job: Minimal Solr Config Example
INFO  [JobSuite] Running Minimal Solr Config Example: END (Sat Sep 03 17:44:03 COT 2016)
FATAL [JobSuite] Job suite execution failed: Minimal Solr Config Example
java.lang.NoSuchFieldError: INSTANCE
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
    at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
    at com.norconex.collector.http.client.impl.GenericHttpClientFactory.createHTTPClient(GenericHttpClientFactory.java:306)
    at com.norconex.collector.http.crawler.HttpCrawler.initializeHTTPClient(HttpCrawler.java:442)
    at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:116)
    at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:204)
    at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:179)
    at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
    at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:350)
    at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:300)
    at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:172)
    at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:120)
    at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:80)
    at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

and also I could not find any document at all

thanks

**Comment by essiembre** [comment] 2016-09-04 17:32
I cannot reproduce.  According to your logs, it fails before it really does anything, so it does not even attempt to send documents to Solr.  The `NoSuchFieldError` could come form library version differences.  Can you look into your "lib" folder and verify that you do not have the same library listed more than once, with different version?   Pay special attention to the "httpclient" library.  The version that ships with the HTTP Collector version you are using should be 4.5.2.

**Comment by angelo337** [comment] 2016-09-04 23:45
hi there 
I just verify that, you are the man!!!, 
i just delete all version of files that i just copy from others collectors and commiters

there is the list of files i delete
rm collector-http/lib/commons-collections4-4.0.jar 
rm collector-http/lib/commons-io-2.4.jar
rm collector-http/lib/commons-lang-2.6.jar 
rm collector-http/lib/commons-lang3-3.3.2.jar 
rm collector-http/lib/commons-logging-1.*.jar
rm collector-http/lib/httpcore-4.2.5.jar 
rm collector-http/lib/httpcore-4.4.1.jar 
rm collector-http/lib/httpcore-4.4.4.jar 
rm collector-http/lib/httpmime-4.2.6.jar 
rm collector-http/lib/zookeeper-3.4.6.jar 

I manange to pass all previous however I am still not able to include any doc's at all in my Solr server. what should I check please?
thanks

**Comment by angelo337** [comment] 2016-09-05 01:27
hi there
Finnaly I manage to get this working, however I am getting for most URL I am trying to crawl a message like this one:
INFO  [CrawlerEventManager]       REJECTED_ROBOTS_TXT: https://es.wikipedia.org/w/index.php?title=1504&action=edit&section=3

could you please point me out some resource to read about it? or could you pleas eexplain for me that message?
thanks

**Comment by essiembre** [comment] 2016-09-05 22:10
Glad you resolved your issue. `REJECTED_ROBOTS_TXT` means the URL is rejected by `robots.txt` rules found for the site: The https://es.wikipedia.org/robots.txt

If you do not want to honor `robots.txt` rules (a "nice" crawler usually tries to honor those) you can disable it by adding the following to your crawler config:

``` xml
<robotsTxt ignore="true"/>
```

You can also change the log level in the `log4j.properties` file to get more information about rejections (like which rule was rejected).  For instance, you can set DEBUG on that line:

```
log4j.logger.CrawlerEvent.REJECTED_ROBOTS_TXT=DEBUG
```

**Comment by essiembre** [comment] 2016-09-05 22:13
Since the original issue from this ticket has been resolved, I am closing it.  If you have other HTTP Collector questions/issues that are not specific to the Solr Committer, please raise them here instead: https://github.com/norconex/collector-http/issues

**Closed as completed by essiembre** 2016-09-05 22:13 UTC
